version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cp ./aws/.npmrc ~/.npmrc
      - sed -i 's/FONT_AWESOME_KEY/${FONT_AWESOME_KEY}/g' ~/.npmrc
      - sed -i 's/GIT_NPM_KEY/${GIT_NPM_KEY}/g' ~/.npmrc
      - yarn install
  pre_build:
    commands:
    - yarn test:ci
  build:
    commands:
    - yarn build

artifacts:
  base-directory: ./build
  files:
    - '**/*'

reports:
  coverage_reports:
    files:
    - ./coverage/clover.xml
    file-format: CLOVERXML