name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
    - name: "Install"
      run: yarn install
    - name: "Test"
      run: yarn test
