name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
    - name: "Setup NPM Registries"
      run: |
        cp .github/.npmrc ~/.npmrc
        sed -i 's/FONT_AWESOME_KEY/${{ secrets.FONT_AWESOME_KEY }}/g' ~/.npmrc
        sed -i 's/GIT_NPM_KEY/${{ secrets.NPM_PAT_TOKEN }}/g' ~/.npmrc
        cat ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_PAT_TOKEN}}
    - name: "Install"
      run: yarn install
    - name: "Test"
      run: yarn test:ci
